[path]
# use absolute path
root="/home/x/Workspace/CorpMagnifier"

# when using the variable, build a full path with
# dbpath = Path(cmconf['path']['root']) / Path(cmconf['path']['db'])
data="data"
db="db/CorpMagnifier.db"

[data]
report_types=[
    '포괄손익계산서',
    '포괄손익계산서-연결',
    '현금흐름표',
    '현금흐름표-연결',
    '손익계산서',
    '손익계산서-연결',
    # '자본변동표',
    # '자본변동표-연결',
    '재무상태표',
    '재무상태표-연결',
]